paths:
  /waves/v1/lightning-large/add_voice:
    post:
      x-fern-server-name: waves
      x-fern-audiences:
        - v4docs
      summary: Add your Voice
      description: Add your voice using the Waves API.