paths:
  /api/v1/lightning-large:
    delete:
      x-fern-server-name: waves
      x-fern-audiences:
        - v4docs
      summary: Delete Cloned Voice
      description: Delete a cloned voice using the new Waves API.
