paths:
  /api/v1/{model}/get_voices:
    get:
      x-fern-server-name: waves
      x-fern-audiences:
        - v4docs
      description: Get voices supported for a given model using the new Waves API.
      parameters:
        - in: path
          name: model
          schema:
            enum:
              - lightning
              - lightning-large
              - lightning-v2
              - lightning-v3.1
