paths:
  /api/v1/pulse/get_text:
    post:
      x-fern-server-name: waves
      x-fern-audiences:
        - v4docs
      x-fern-sdk-group-name: Speech to Text
      x-fern-sdk-method-name: pulse
      operationId: pulseSpeechToText
      tags:
        - Speech to Text
      summary: Pulse (Pre-Recorded)
      responses:
        "413":
          content:
            application/json:
              example:
                error:
                  code: "413"
                  message: "File size exceeds maximum limit of 25MB"
                status: error
        "429":
          content:
            application/json:
              example:
                error:
                  code: "429"
                  message: "Rate limit exceeded. Please try again later."
                status: error
