paths:
  /waves/v1/stt/:
    post:
      x-fern-server-name: waves
      x-fern-audiences:
      - v4docs
      x-fern-sdk-group-name: Speech to Text
      operationId: transcribe
      tags:
      - Speech to Text
      summary: Transcribe (Pulse or Pulse Pro)
      responses:
        '413':
          content:
            application/json:
              example:
                status: error
                message: File size exceeds maximum limit of 25MB.
        '429':
          content:
            application/json:
              example:
                status: error
                message: Rate limit exceeded. Please retry after a short backoff.
