paths:
  /waves/v1/text-intelligence:
    post:
      x-fern-server-name: waves
      x-fern-audiences:
        - v4docs
      x-fern-sdk-group-name: Text Intelligence
      x-fern-sdk-method-name: analyze
      tags:
        - Text Intelligence
