#!/usr/bin/env python3
"""
Compare two Fern IR dumps and report what changed in the API surface.

Use this to prove that a spec refactor (splitting a file, moving schemas,
reordering paths) does not change what the SDK generators see:

    cd fern
    fern ir /tmp/before.json --api unified      # on main
    git checkout <branch>
    fern ir /tmp/after.json --api unified
    python3 scripts/spec-live-tests/ir_equivalence.py /tmp/before.json /tmp/after.json

Exit code 0 when endpoints, types, and error shapes are identical. Exit code 1
when anything structural differs. Docstring-only and example-order differences
are reported separately and do not fail the check, because Fern resolves
those "first seen wins" across files and they never change generated code.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def canon(o) -> str:
    return json.dumps(o, sort_keys=True)


def strip_cosmetic(o):
    """Drop docs strings and example lists so only structure is compared."""
    if isinstance(o, dict):
        return {k: strip_cosmetic(v) for k, v in o.items() if k not in ("docs", "examples", "userSpecifiedExamples", "autogeneratedExamples")}
    if isinstance(o, list):
        return [strip_cosmetic(i) for i in o]
    return o


def ename(e) -> str:
    n = e.get("name")
    return n["originalName"] if isinstance(n, dict) else str(n)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    b = json.load(open(Path(sys.argv[1])))
    a = json.load(open(Path(sys.argv[2])))
    be = {(sid, ename(e)): e for sid, s in b["services"].items() for e in s["endpoints"]}
    ae = {(sid, ename(e)): e for sid, s in a["services"].items() for e in s["endpoints"]}
    bt, at = b.get("types", {}), a.get("types", {})
    berr, aerr = b.get("errors", {}), a.get("errors", {})

    structural: list[str] = []
    cosmetic: list[str] = []

    for label, bd, ad in (("endpoint", be, ae), ("type", bt, at), ("error", berr, aerr)):
        for k in sorted(set(bd) - set(ad)):
            structural.append(f"{label} removed: {k}")
        for k in sorted(set(ad) - set(bd)):
            structural.append(f"{label} added: {k}")
        for k in sorted(set(bd) & set(ad)):
            if canon(bd[k]) == canon(ad[k]):
                continue
            if canon(strip_cosmetic(bd[k])) == canon(strip_cosmetic(ad[k])):
                cosmetic.append(f"{label} {k}: docs or example order only")
            else:
                structural.append(f"{label} changed: {k}")

    print(f"endpoints {len(be)} -> {len(ae)} | types {len(bt)} -> {len(at)} | errors {len(berr)} -> {len(aerr)}")
    if cosmetic:
        print(f"\n{len(cosmetic)} cosmetic difference(s) (do not affect generated code):")
        for c in cosmetic:
            print("  -", c)
    if structural:
        print(f"\n{len(structural)} STRUCTURAL difference(s):")
        for s in structural:
            print("  -", s)
        return 1
    print("\nOK: API surface is identical.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
