# Override file for asr-openapi.yaml
# Renames the 'transcription' property to 'text' in SpeechToTextResponse

paths:
  /api/v1/lightning/get_text:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  transcription:
                    x-fern-property-name: text
