# Override file for asr-openapi.yaml
# Renames the 'transcription' property to 'text' in SpeechToTextResponse
# Specifies waves server for all endpoints

paths:
  /api/v1/lightning/get_text:
    post:
      x-fern-server-name: waves
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  transcription:
                    x-fern-property-name: text
        "413":
          x-fern-ignore: true
        "429":
          x-fern-ignore: true
