paths:
  /waves/v1/lightning-large:
    delete:
      operationId: delete_voice
      x-fern-sdk-method-name: delete_voice
      x-fern-server-name: waves
      x-fern-audiences:
        - v2
        - v3
        - v4
      summary: Delete Cloned Voice
      description: Delete a cloned voice using the new Waves API.
