paths:
  /waves/v1/lightning-large/get_cloned_voices:
    get:
      operationId: get_cloned_voices
      x-fern-sdk-method-name: get_cloned_voices
      x-fern-server-name: waves
      x-fern-audiences:
        - v2
        - v3
        - v4
      summary: Get your cloned Voices
      description: Retrieve your cloned voices.
