# Override file for get-cloned-voices-openapi.yaml
# Specifies waves server for all endpoints

paths:
  /api/v1/lightning-large/get_cloned_voices:
    get:
      x-fern-server-name: waves
      description: |
        Retrieve your cloned voices.
