paths:
  /waves/v1/lightning-v3.1/get_speech:
    post:
      deprecated: true
      operationId: synthesize_lightning_v3_1
      x-fern-sdk-method-name: synthesize_lightning_v3_1
      x-fern-server-name: waves
      x-fern-audiences:
      - v4
      tags:
      - Text to Speech
      summary: Generate speech (Lightning v3.1, Endpoint Deprecated)
  /waves/v1/lightning-v3.1/stream:
    post:
      deprecated: true
      operationId: synthesize_sse_lightning_v3_1
      x-fern-sdk-method-name: synthesize_sse_lightning_v3_1
      x-fern-server-name: waves
      x-fern-audiences:
      - v4
      tags:
      - Text to Speech
      summary: Stream speech (Lightning v3.1 SSE, Endpoint Deprecated)
components:
  schemas:
    LightningV31Request:
      properties:
        output_format:
          enum:
          - mp3
          - pcm
          - wav
          - ulaw
          - alaw
        sample_rate:
          enum:
          - 8000
          - 16000
          - 24000
          - 44100
