paths:
  /waves/v1/tts:
    post:
      operationId: synthesize_tts
      x-fern-sdk-method-name: synthesize_tts
      x-fern-server-name: waves
      x-fern-audiences:
      - v4
      tags:
      - Text to Speech
      summary: Synthesize speech
  /waves/v1/tts/live:
    post:
      operationId: synthesize_sse_tts
      x-fern-sdk-method-name: synthesize_sse_tts
      x-fern-server-name: waves
      x-fern-audiences:
      - v4
      tags:
      - Text to Speech
      summary: Stream speech (SSE)
