paths:
  /waves/v1/voice-cloning:
    post:
      operationId: create_voice_clone
      x-fern-sdk-method-name: create_voice_clone
      x-fern-server-name: waves
      x-fern-audiences:
        - v4
      summary: Create a Voice Clone
      description: |
        Create an instant voice clone in a single call. Defaults to `lightning-v3.1`.
    get:
      operationId: list_voice_clones
      x-fern-sdk-method-name: list_voice_clones
      x-fern-server-name: waves
      x-fern-audiences:
        - v4
      summary: List Voice Clones
      description: |
        Retrieve all voice clones in your organization.
