name: fern-check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern CLI tool
        run: |
          npm uninstall -g fern-api || true
          npm cache clean --force
          npm install -g fern-api@5.7.6
          fern --version

      - name: Check API is valid
        run: fern check
