name: fern-check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check API is valid
        run: |
          npx --yes fern-api@5.7.6 --version
          npx --yes fern-api@5.7.6 check
